# Generated by Django 4.2.4 on 2023-09-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='file',
            field=models.FileField(default=1, upload_to='attachments/'),
            preserve_default=False,
        ),
    ]
