# Generated by Django 2.2 on 2023-09-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0003_auto_20230904_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='Deskripsi Laporan'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Minor', 'Minor'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Minor', max_length=20),
        ),
    ]
