# Generated by Django 2.2 on 2023-09-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0004_auto_20230904_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='Upload File Pendukung'),
        ),
    ]
