# Generated by Django 4.2.4 on 2023-09-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0005_alter_ticket_position_alter_ticket_reporter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='position',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Proses', 'Terkirim Ke Support'), ('Diteruskan ke Pengembang', 'Tiket Dari Support'), ('Selesai', 'Selesai'), ('Kembalikan ke Support', 'Kembalikan Dari Developer')], default='Proses', max_length=55),
        ),
    ]
