# Generated by Django 4.2.4 on 2023-09-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0006_remove_ticket_position_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Proses', 'Terkirim Ke Support'), ('ToDeveloper', 'Tiket Dari Support'), ('Selesai', 'Selesai'), ('ToSupport', 'Tiket Dari Developer')], default='Proses', max_length=55),
        ),
    ]
